[MULTILINE_PARSER]
    Name          oracle_xml_multiline
    Type          regex
    # Increase Flush_Timeout if your log messages can be very long
    Flush_Timeout 1000

    # Rules to define how to merge lines
    # ---------------------------------
    # rules | state name | regex pattern       | next state
    # ------|------------|---------------------|-----------
    # Start: Match the beginning of a message: <msg...
    Rule "start_state" "/^<msg\s+time='.+?'.*$/" "cont"
    # Continuation: Match any line until the start of a *new* message
    # (using a negative lookahead)
    Rule "cont"      "/^(?!\<msg\s+time=).*$/" "cont"

[MULTILINE_PARSER]
    name          postgresql_multiline
    type          regex
    flush_timeout 1000

    # YYYY-MM-DD HH:MM:SS.msmsms TIMEZONE,"username",...
    #
    # Regex for a *new* line (START of a log record):
    # ^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.*$
    #
    # Continuation: Match any line until the start of a *new* message
    # (using a negative lookahead)
    # ^(?!\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.*$)
    rule      "start_state"   "/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.*$/"  "cont"
    rule      "cont"          "/^(?!\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}).*$/" "cont"

[MULTILINE_PARSER]
    Name freeradius_accounting_multiline
    type          regex
    flush_timeout 1000

    #
    # Multiline parser for freeradius accounting logs.
    # A tipical freeradius accounting log looks like this:
    #
    # Thu Nov 27 13:28:28 2025
    #      Framed-IP-Address = 193.157.239.14
    #      Framed-IPv6-Address = fe80::c52:6949:a41:e30b
    #      User-Name = "xxxxxx@uio.no"
    #      Called-Station-Id = "90-eb-50-63-89-0b"
    #      Calling-Station-Id = "de-47-10-39-a5-b0"
    #      NAS-IP-Address = 129.240.112.26
    #      NAS-Port-Id = "capwap_9100073c"
    #      NAS-Identifier = "bl10-550-ap:eduroam"
    #      Acct-Terminate-Cause = User-Error
    #      Acct-Status-Type = Stop
    #      Event-Timestamp = "Nov 27 2025 13:28:28 CET"
    #      Timestamp = 1764246508
    #
    # start_state matcher:
    # Tue Dec  9 03:20:03 2025
    # Tue Dec 19 03:20:03 2025
    #

    rule      "start_state"   "/^[A-Za-z]{3}\s*[A-Za-z]{3}\s*(\d{1}|\d{2})\s*\d{2}:\d{2}:\d{2}\s*\d{4}.*$/"  "cont"
    rule      "cont"          "/^\t.*$/" "cont"
