---
include:
  default:
    - profile::storage::cephmon
    - profile::storage::cephmon_firewall
  bootstrap:
    - profile::storage::cephmon_firewall

profile::storage::cephmon_firewall::manage_firewall:  true

accounts::users:
  'cinder':
    ensure: present
  'glance':
    ensure: present
  'nova':
    ensure: present

accounts::usergroups:
  'cinder':
    - 'cinder'
  'glance':
    - 'glance'
  'nova':
    - 'nova'

accounts::accounts:
  'cinder':
    ensure: present
  'glance':
    ensure: present
  'nova':
    ensure: present
