---
include:
  default:
    - profile::openstack::compute::hypervisor
    - profile::openstack::volume
    - nova::compute::rbd
    - ceph::profile::client
    - profile::application::etcd
    - cinder::backends
    - profile::application::consul

profile::base::common::manage_lvm: true
etcd::initial_cluster: ["%{hiera('service__address__etcd_cluster')}"]
etcd::mode: 'proxy'

mgmt_interface: 'em3'
mgmt_address:   "%{ipaddress_em3}"

lvm::logical_volume:
  lv_instances:
    volume_group: vg_root
    fs_type: xfs
    mountpath: /var/lib/nova/instances

sudo::purge: false

accounts::users:
  'cinder':
    ensure: present
  'glance':
    ensure: present

accounts::usergroups:
  'cinder':
    - 'cinder'
  'glance':
    - 'glance'

accounts::accounts:
  'cinder':
    ensure: present
  'glance':
    ensure: present
